<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Automation.Files.Contracts\Automation.Files.Contracts.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\Automation.SharedKernel\Automation.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Automation.Api" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>


