# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import execution_state_pb2 as execution__state__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in execution_state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutionStateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStepInputs = channel.unary_unary(
                '/automation.pipeline.ExecutionStateService/GetStepInputs',
                request_serializer=execution__state__pb2.GetStepInputsRequest.SerializeToString,
                response_deserializer=execution__state__pb2.GetStepInputsResponse.FromString,
                _registered_method=True)
        self.ReportStepOutput = channel.unary_unary(
                '/automation.pipeline.ExecutionStateService/ReportStepOutput',
                request_serializer=execution__state__pb2.ReportStepOutputRequest.SerializeToString,
                response_deserializer=execution__state__pb2.ReportStepOutputResponse.FromString,
                _registered_method=True)


class ExecutionStateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStepInputs(self, request, context):
        """Agent requests resolved input values for a step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStepOutput(self, request, context):
        """Agent reports step execution outputs and logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStepInputs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStepInputs,
                    request_deserializer=execution__state__pb2.GetStepInputsRequest.FromString,
                    response_serializer=execution__state__pb2.GetStepInputsResponse.SerializeToString,
            ),
            'ReportStepOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStepOutput,
                    request_deserializer=execution__state__pb2.ReportStepOutputRequest.FromString,
                    response_serializer=execution__state__pb2.ReportStepOutputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.pipeline.ExecutionStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('automation.pipeline.ExecutionStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutionStateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStepInputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automation.pipeline.ExecutionStateService/GetStepInputs',
            execution__state__pb2.GetStepInputsRequest.SerializeToString,
            execution__state__pb2.GetStepInputsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStepOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automation.pipeline.ExecutionStateService/ReportStepOutput',
            execution__state__pb2.ReportStepOutputRequest.SerializeToString,
            execution__state__pb2.ReportStepOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
