import { keepPreviousData } from "@tanstack/react-query";
import { createMutationHook } from "@/lib/query-utils";
import * as RunnersApi from "@/gen/endpoints/runners/runners";
import type {
  RunnerDto,
  RunnerDto2,
  RunnerHardwareProfile,
  RunnerGpuInfo,
  RunnerDiskInfo,
  ExecutorCandidateDto,
  RunnerExecutorConfigDto,
  SetupTokenDto,
  AttachRunnerToStudioRequest,
} from "../types";
import type { DiscoverRunnerFoldersParams } from "@/gen/model";

export type {
  RunnerDto,
  RunnerDto2,
  RunnerHardwareProfile,
  RunnerGpuInfo,
  RunnerDiskInfo,
  ExecutorCandidateDto,
  RunnerExecutorConfigDto,
  SetupTokenDto,
  AttachRunnerToStudioRequest,
};

export const useRunners = () => {
  return RunnersApi.useGetRunners<RunnerDto[]>({
    query: {
      placeholderData: keepPreviousData,
      select: (data) => data as unknown as RunnerDto[],
    },
  });
};

export const useStudioRunners = (studioId?: string) => {
  return RunnersApi.useGetStudioRunners<RunnerDto[]>(
    studioId || "",
    {
      query: {
        enabled: !!studioId,
        placeholderData: keepPreviousData,
        select: (data: any) => {
          const list = Array.isArray(data) ? data : data?.items || [];
          return list
            .filter((item: any) => item && (item.runner || item.runnerId))
            .map((item: any) => {
              const r = item.runner || {};
              return {
                ...r,
                id: item.runnerId || r.id,
                name: item.alias || r.name || "Runner",
                machineKey: r.machineKey || "",
                executorConfigs: r.executorConfigs || [],
              } as RunnerDto;
            });
        },
      },
    }
  );
};

export const useDiscoverRunnerFolder = (
  id: string,
  pathOrParams?: string | DiscoverRunnerFoldersParams
) => {
  const params: DiscoverRunnerFoldersParams | undefined =
    typeof pathOrParams === "string"
      ? { path: pathOrParams }
      : pathOrParams;

  return RunnersApi.useDiscoverRunnerFolders(
    id,
    params,
    {
      query: {
        enabled: !!id,
        placeholderData: keepPreviousData,
      },
    }
  );
};

export const useGenerateSetupToken = createMutationHook(
  RunnersApi.useGenerateSetupToken,
  [RunnersApi.getGetRunnersQueryKey()]
);

export const useAttachRunnerToStudio = createMutationHook(
  RunnersApi.useAttachRunnerToStudio,
  [RunnersApi.getGetRunnersQueryKey()]
);

/**
 * Mutation hook to remotely trigger a hardware rescan on a specific runner.
 * Auto-generated by Orval and wrapped via createMutationHook factory.
 */
export const useScanRunnerHardware = createMutationHook(
  RunnersApi.useScanRunnerHardware,
  [RunnersApi.getGetRunnersQueryKey()]
);

/**
 * Mutation hook to remotely trigger DCC software scanner (Blender, Unreal, Python).
 * Auto-generated by Orval and wrapped via createMutationHook factory.
 */
export const useScanRunnerExecutors = createMutationHook(
  RunnersApi.useScanExecutors,
  [RunnersApi.getGetRunnersQueryKey()]
);

/**
 * Mutation hook to configure and save an active executor runtime (e.g. choose Blender 4.2 or Unreal 5.4) on a runner.
 */
export const useConfigureRunnerExecutor = createMutationHook(
  RunnersApi.useConfigureRunnerExecutor,
  [RunnersApi.getGetRunnersQueryKey()]
);
