<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\..\..\SharedKernel\Automation.SharedKernel\Automation.SharedKernel.csproj" />
      <ProjectReference Include="..\Automation.Projects.Contracts\Automation.Projects.Contracts.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Automation.Api" />
    </ItemGroup>

</Project>
