/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/_layout'
import { Route as ProtectedProjectRouteImport } from './routes/_protected/_project'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth/accept-invite'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as ProtectedLayoutIndexRouteImport } from './routes/_protected/_layout/index'
import { Route as ProtectedLayout403RouteImport } from './routes/_protected/_layout/403'
import { Route as ProtectedLayoutDevRouteImport } from './routes/_protected/_layout/dev'
import { Route as ProtectedLayoutRolesRouteRouteImport } from './routes/_protected/_layout/roles/route'
import { Route as ProtectedLayoutRunnersRouteImport } from './routes/_protected/_layout/runners'
import { Route as ProtectedLayoutSettingsRouteRouteImport } from './routes/_protected/_layout/settings/route'
import { Route as ProtectedLayoutUsersRouteRouteImport } from './routes/_protected/_layout/users/route'
import { Route as ProtectedLayoutRolesIndexRouteImport } from './routes/_protected/_layout/roles/index'
import { Route as ProtectedLayoutSettingsIndexRouteImport } from './routes/_protected/_layout/settings/index'
import { Route as ProtectedLayoutSettingsNotificationsRouteImport } from './routes/_protected/_layout/settings/notifications'
import { Route as ProtectedLayoutSettingsProfileRouteImport } from './routes/_protected/_layout/settings/profile'
import { Route as ProtectedLayoutSettingsSecurityRouteImport } from './routes/_protected/_layout/settings/security'
import { Route as ProtectedLayoutSystemAuditLogsRouteImport } from './routes/_protected/_layout/system/audit-logs'
import { Route as ProtectedLayoutSystemSettingsRouteImport } from './routes/_protected/_layout/system/settings'
import { Route as ProtectedLayoutUsersIndexRouteImport } from './routes/_protected/_layout/users/index'
import { Route as ProtectedLayoutUsersNewRouteImport } from './routes/_protected/_layout/users/new'
import { Route as ProtectedLayoutSStudioSlugIndexRouteImport } from './routes/_protected/_layout/s/$studioSlug/index'
import { Route as ProtectedLayoutSStudioSlugRunnersRouteImport } from './routes/_protected/_layout/s/$studioSlug/runners'
import { Route as ProtectedLayoutSystemAuditLogsIndexRouteImport } from './routes/_protected/_layout/system/audit-logs/index'
import { Route as ProtectedLayoutSystemAuditLogsIdRouteImport } from './routes/_protected/_layout/system/audit-logs/$id'
import { Route as ProtectedLayoutUsersIdIndexRouteImport } from './routes/_protected/_layout/users/$id/index'
import { Route as ProtectedLayoutUsersIdEditRouteImport } from './routes/_protected/_layout/users/$id/edit'
import { Route as ProtectedLayoutSStudioSlugProjectsIndexRouteImport } from './routes/_protected/_layout/s/$studioSlug/projects/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/route'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/content-types'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/contents'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdOverviewRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/overview'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/repositories'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/structs'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/content-types/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/contents/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/$pipelineId'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/repositories/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/repositories/$repositoryId'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/resources/$resourceId'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/structs/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/new'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/index'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/new'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/structs/$structId/builder'
import { Route as ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRouteImport } from './routes/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectRoute = ProtectedProjectRouteImport.update({
  id: '/_project',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedLayoutIndexRoute = ProtectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayout403Route = ProtectedLayout403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutDevRoute = ProtectedLayoutDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutRolesRouteRoute =
  ProtectedLayoutRolesRouteRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutRunnersRoute = ProtectedLayoutRunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutSettingsRouteRoute =
  ProtectedLayoutSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutUsersRouteRoute =
  ProtectedLayoutUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutRolesIndexRoute =
  ProtectedLayoutRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutRolesRouteRoute,
  } as any)
const ProtectedLayoutSettingsIndexRoute =
  ProtectedLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSettingsNotificationsRoute =
  ProtectedLayoutSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSettingsProfileRoute =
  ProtectedLayoutSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSettingsSecurityRoute =
  ProtectedLayoutSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSystemAuditLogsRoute =
  ProtectedLayoutSystemAuditLogsRouteImport.update({
    id: '/system/audit-logs',
    path: '/system/audit-logs',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutSystemSettingsRoute =
  ProtectedLayoutSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutUsersIndexRoute =
  ProtectedLayoutUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutUsersRouteRoute,
  } as any)
const ProtectedLayoutUsersNewRoute = ProtectedLayoutUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedLayoutUsersRouteRoute,
} as any)
const ProtectedLayoutSStudioSlugIndexRoute =
  ProtectedLayoutSStudioSlugIndexRouteImport.update({
    id: '/s/$studioSlug/',
    path: '/s/$studioSlug/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutSStudioSlugRunnersRoute =
  ProtectedLayoutSStudioSlugRunnersRouteImport.update({
    id: '/s/$studioSlug/runners',
    path: '/s/$studioSlug/runners',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutSystemAuditLogsIndexRoute =
  ProtectedLayoutSystemAuditLogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutSystemAuditLogsRoute,
  } as any)
const ProtectedLayoutSystemAuditLogsIdRoute =
  ProtectedLayoutSystemAuditLogsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedLayoutSystemAuditLogsRoute,
  } as any)
const ProtectedLayoutUsersIdIndexRoute =
  ProtectedLayoutUsersIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => ProtectedLayoutUsersRouteRoute,
  } as any)
const ProtectedLayoutUsersIdEditRoute =
  ProtectedLayoutUsersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => ProtectedLayoutUsersRouteRoute,
  } as any)
const ProtectedLayoutSStudioSlugProjectsIndexRoute =
  ProtectedLayoutSStudioSlugProjectsIndexRouteImport.update({
    id: '/s/$studioSlug/projects/',
    path: '/s/$studioSlug/projects/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteImport.update({
    id: '/s/$studioSlug/projects/$projectId',
    path: '/s/$studioSlug/projects/$projectId',
    getParentRoute: () => ProtectedProjectRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteImport.update({
    id: '/content-types',
    path: '/content-types',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteImport.update({
    id: '/contents',
    path: '/contents',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteImport.update({
    id: '/structs',
    path: '/structs',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteImport.update(
    {
      id: '/$typeKey',
      path: '/$typeKey',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRouteImport.update(
    {
      id: '/pipeline/$pipelineId',
      path: '/pipeline/$pipelineId',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRouteImport.update(
    {
      id: '/$repositoryId',
      path: '/$repositoryId',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRouteImport.update(
    {
      id: '/resources/$resourceId',
      path: '/resources/$resourceId',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute,
  } as any)
const ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRouteImport.update(
    {
      id: '/$contentTypeId/',
      path: '/$contentTypeId/',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRouteImport.update(
    {
      id: '/$contentTypeId/builder',
      path: '/$contentTypeId/builder',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRouteImport.update(
    {
      id: '/new',
      path: '/new',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRouteImport.update(
    {
      id: '/pipeline/nodes/',
      path: '/pipeline/nodes/',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRouteImport.update(
    {
      id: '/pipeline/nodes/ingest',
      path: '/pipeline/nodes/ingest',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRouteImport.update(
    {
      id: '/pipeline/nodes/new',
      path: '/pipeline/nodes/new',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRouteImport.update(
    {
      id: '/$structId/builder',
      path: '/$structId/builder',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute,
    } as any,
  )
const ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRouteImport.update(
    {
      id: '/$itemKey/edit',
      path: '/$itemKey/edit',
      getParentRoute: () =>
        ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof ProtectedLayoutIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/roles': typeof ProtectedLayoutRolesRouteRouteWithChildren
  '/settings': typeof ProtectedLayoutSettingsRouteRouteWithChildren
  '/users': typeof ProtectedLayoutUsersRouteRouteWithChildren
  '/403': typeof ProtectedLayout403Route
  '/dev': typeof ProtectedLayoutDevRoute
  '/runners': typeof ProtectedLayoutRunnersRoute
  '/settings/notifications': typeof ProtectedLayoutSettingsNotificationsRoute
  '/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/settings/security': typeof ProtectedLayoutSettingsSecurityRoute
  '/system/audit-logs': typeof ProtectedLayoutSystemAuditLogsRouteWithChildren
  '/system/settings': typeof ProtectedLayoutSystemSettingsRoute
  '/users/new': typeof ProtectedLayoutUsersNewRoute
  '/roles/': typeof ProtectedLayoutRolesIndexRoute
  '/settings/': typeof ProtectedLayoutSettingsIndexRoute
  '/users/': typeof ProtectedLayoutUsersIndexRoute
  '/s/$studioSlug/runners': typeof ProtectedLayoutSStudioSlugRunnersRoute
  '/system/audit-logs/$id': typeof ProtectedLayoutSystemAuditLogsIdRoute
  '/users/$id/edit': typeof ProtectedLayoutUsersIdEditRoute
  '/s/$studioSlug/': typeof ProtectedLayoutSStudioSlugIndexRoute
  '/system/audit-logs/': typeof ProtectedLayoutSystemAuditLogsIndexRoute
  '/users/$id/': typeof ProtectedLayoutUsersIdIndexRoute
  '/s/$studioSlug/projects/$projectId': typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteWithChildren
  '/s/$studioSlug/projects/': typeof ProtectedLayoutSStudioSlugProjectsIndexRoute
  '/s/$studioSlug/projects/$projectId/content-types': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteWithChildren
  '/s/$studioSlug/projects/$projectId/contents': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteWithChildren
  '/s/$studioSlug/projects/$projectId/overview': typeof ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute
  '/s/$studioSlug/projects/$projectId/repositories': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteWithChildren
  '/s/$studioSlug/projects/$projectId/structs': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteWithChildren
  '/s/$studioSlug/projects/$projectId/contents/$typeKey': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteWithChildren
  '/s/$studioSlug/projects/$projectId/pipeline/$pipelineId': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute
  '/s/$studioSlug/projects/$projectId/repositories/$repositoryId': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute
  '/s/$studioSlug/projects/$projectId/resources/$resourceId': typeof ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute
  '/s/$studioSlug/projects/$projectId/content-types/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute
  '/s/$studioSlug/projects/$projectId/contents/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute
  '/s/$studioSlug/projects/$projectId/pipeline/': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute
  '/s/$studioSlug/projects/$projectId/repositories/': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute
  '/s/$studioSlug/projects/$projectId/structs/': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute
  '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  '/s/$studioSlug/projects/$projectId/contents/$typeKey/new': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute
  '/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute
  '/s/$studioSlug/projects/$projectId/pipeline/nodes/new': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute
  '/s/$studioSlug/projects/$projectId/structs/$structId/builder': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute
  '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute
  '/s/$studioSlug/projects/$projectId/contents/$typeKey/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute
  '/s/$studioSlug/projects/$projectId/pipeline/nodes/': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute
  '/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedLayoutIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/403': typeof ProtectedLayout403Route
  '/dev': typeof ProtectedLayoutDevRoute
  '/runners': typeof ProtectedLayoutRunnersRoute
  '/settings/notifications': typeof ProtectedLayoutSettingsNotificationsRoute
  '/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/settings/security': typeof ProtectedLayoutSettingsSecurityRoute
  '/system/settings': typeof ProtectedLayoutSystemSettingsRoute
  '/users/new': typeof ProtectedLayoutUsersNewRoute
  '/roles': typeof ProtectedLayoutRolesIndexRoute
  '/settings': typeof ProtectedLayoutSettingsIndexRoute
  '/users': typeof ProtectedLayoutUsersIndexRoute
  '/s/$studioSlug/runners': typeof ProtectedLayoutSStudioSlugRunnersRoute
  '/system/audit-logs/$id': typeof ProtectedLayoutSystemAuditLogsIdRoute
  '/users/$id/edit': typeof ProtectedLayoutUsersIdEditRoute
  '/s/$studioSlug': typeof ProtectedLayoutSStudioSlugIndexRoute
  '/system/audit-logs': typeof ProtectedLayoutSystemAuditLogsIndexRoute
  '/users/$id': typeof ProtectedLayoutUsersIdIndexRoute
  '/s/$studioSlug/projects/$projectId': typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteWithChildren
  '/s/$studioSlug/projects': typeof ProtectedLayoutSStudioSlugProjectsIndexRoute
  '/s/$studioSlug/projects/$projectId/overview': typeof ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute
  '/s/$studioSlug/projects/$projectId/pipeline/$pipelineId': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute
  '/s/$studioSlug/projects/$projectId/repositories/$repositoryId': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute
  '/s/$studioSlug/projects/$projectId/resources/$resourceId': typeof ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute
  '/s/$studioSlug/projects/$projectId/content-types': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute
  '/s/$studioSlug/projects/$projectId/contents': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute
  '/s/$studioSlug/projects/$projectId/pipeline': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute
  '/s/$studioSlug/projects/$projectId/repositories': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute
  '/s/$studioSlug/projects/$projectId/structs': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute
  '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  '/s/$studioSlug/projects/$projectId/contents/$typeKey/new': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute
  '/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute
  '/s/$studioSlug/projects/$projectId/pipeline/nodes/new': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute
  '/s/$studioSlug/projects/$projectId/structs/$structId/builder': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute
  '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute
  '/s/$studioSlug/projects/$projectId/contents/$typeKey': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute
  '/s/$studioSlug/projects/$projectId/pipeline/nodes': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute
  '/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/_protected/_project': typeof ProtectedProjectRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_protected/_layout/roles': typeof ProtectedLayoutRolesRouteRouteWithChildren
  '/_protected/_layout/settings': typeof ProtectedLayoutSettingsRouteRouteWithChildren
  '/_protected/_layout/users': typeof ProtectedLayoutUsersRouteRouteWithChildren
  '/_protected/_layout/403': typeof ProtectedLayout403Route
  '/_protected/_layout/dev': typeof ProtectedLayoutDevRoute
  '/_protected/_layout/runners': typeof ProtectedLayoutRunnersRoute
  '/_protected/_layout/': typeof ProtectedLayoutIndexRoute
  '/_protected/_layout/settings/notifications': typeof ProtectedLayoutSettingsNotificationsRoute
  '/_protected/_layout/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/_protected/_layout/settings/security': typeof ProtectedLayoutSettingsSecurityRoute
  '/_protected/_layout/system/audit-logs': typeof ProtectedLayoutSystemAuditLogsRouteWithChildren
  '/_protected/_layout/system/settings': typeof ProtectedLayoutSystemSettingsRoute
  '/_protected/_layout/users/new': typeof ProtectedLayoutUsersNewRoute
  '/_protected/_layout/roles/': typeof ProtectedLayoutRolesIndexRoute
  '/_protected/_layout/settings/': typeof ProtectedLayoutSettingsIndexRoute
  '/_protected/_layout/users/': typeof ProtectedLayoutUsersIndexRoute
  '/_protected/_layout/s/$studioSlug/runners': typeof ProtectedLayoutSStudioSlugRunnersRoute
  '/_protected/_layout/system/audit-logs/$id': typeof ProtectedLayoutSystemAuditLogsIdRoute
  '/_protected/_layout/users/$id/edit': typeof ProtectedLayoutUsersIdEditRoute
  '/_protected/_layout/s/$studioSlug/': typeof ProtectedLayoutSStudioSlugIndexRoute
  '/_protected/_layout/system/audit-logs/': typeof ProtectedLayoutSystemAuditLogsIndexRoute
  '/_protected/_layout/users/$id/': typeof ProtectedLayoutUsersIdIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId': typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteWithChildren
  '/_protected/_layout/s/$studioSlug/projects/': typeof ProtectedLayoutSStudioSlugProjectsIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/content-types': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteWithChildren
  '/_protected/_project/s/$studioSlug/projects/$projectId/contents': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteWithChildren
  '/_protected/_project/s/$studioSlug/projects/$projectId/overview': typeof ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/repositories': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteWithChildren
  '/_protected/_project/s/$studioSlug/projects/$projectId/structs': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteWithChildren
  '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteWithChildren
  '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/$pipelineId': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/$repositoryId': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/resources/$resourceId': typeof ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/contents/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/': typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/structs/': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/new': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/new': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/structs/$structId/builder': typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/': typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute
  '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit': typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/roles'
    | '/settings'
    | '/users'
    | '/403'
    | '/dev'
    | '/runners'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/system/audit-logs'
    | '/system/settings'
    | '/users/new'
    | '/roles/'
    | '/settings/'
    | '/users/'
    | '/s/$studioSlug/runners'
    | '/system/audit-logs/$id'
    | '/users/$id/edit'
    | '/s/$studioSlug/'
    | '/system/audit-logs/'
    | '/users/$id/'
    | '/s/$studioSlug/projects/$projectId'
    | '/s/$studioSlug/projects/'
    | '/s/$studioSlug/projects/$projectId/content-types'
    | '/s/$studioSlug/projects/$projectId/contents'
    | '/s/$studioSlug/projects/$projectId/overview'
    | '/s/$studioSlug/projects/$projectId/repositories'
    | '/s/$studioSlug/projects/$projectId/structs'
    | '/s/$studioSlug/projects/$projectId/contents/$typeKey'
    | '/s/$studioSlug/projects/$projectId/pipeline/$pipelineId'
    | '/s/$studioSlug/projects/$projectId/repositories/$repositoryId'
    | '/s/$studioSlug/projects/$projectId/resources/$resourceId'
    | '/s/$studioSlug/projects/$projectId/content-types/'
    | '/s/$studioSlug/projects/$projectId/contents/'
    | '/s/$studioSlug/projects/$projectId/pipeline/'
    | '/s/$studioSlug/projects/$projectId/repositories/'
    | '/s/$studioSlug/projects/$projectId/structs/'
    | '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder'
    | '/s/$studioSlug/projects/$projectId/contents/$typeKey/new'
    | '/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest'
    | '/s/$studioSlug/projects/$projectId/pipeline/nodes/new'
    | '/s/$studioSlug/projects/$projectId/structs/$structId/builder'
    | '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/'
    | '/s/$studioSlug/projects/$projectId/contents/$typeKey/'
    | '/s/$studioSlug/projects/$projectId/pipeline/nodes/'
    | '/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/403'
    | '/dev'
    | '/runners'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/system/settings'
    | '/users/new'
    | '/roles'
    | '/settings'
    | '/users'
    | '/s/$studioSlug/runners'
    | '/system/audit-logs/$id'
    | '/users/$id/edit'
    | '/s/$studioSlug'
    | '/system/audit-logs'
    | '/users/$id'
    | '/s/$studioSlug/projects/$projectId'
    | '/s/$studioSlug/projects'
    | '/s/$studioSlug/projects/$projectId/overview'
    | '/s/$studioSlug/projects/$projectId/pipeline/$pipelineId'
    | '/s/$studioSlug/projects/$projectId/repositories/$repositoryId'
    | '/s/$studioSlug/projects/$projectId/resources/$resourceId'
    | '/s/$studioSlug/projects/$projectId/content-types'
    | '/s/$studioSlug/projects/$projectId/contents'
    | '/s/$studioSlug/projects/$projectId/pipeline'
    | '/s/$studioSlug/projects/$projectId/repositories'
    | '/s/$studioSlug/projects/$projectId/structs'
    | '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder'
    | '/s/$studioSlug/projects/$projectId/contents/$typeKey/new'
    | '/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest'
    | '/s/$studioSlug/projects/$projectId/pipeline/nodes/new'
    | '/s/$studioSlug/projects/$projectId/structs/$structId/builder'
    | '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId'
    | '/s/$studioSlug/projects/$projectId/contents/$typeKey'
    | '/s/$studioSlug/projects/$projectId/pipeline/nodes'
    | '/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/_layout'
    | '/_protected/_project'
    | '/_protected/onboarding'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/_protected/_layout/roles'
    | '/_protected/_layout/settings'
    | '/_protected/_layout/users'
    | '/_protected/_layout/403'
    | '/_protected/_layout/dev'
    | '/_protected/_layout/runners'
    | '/_protected/_layout/'
    | '/_protected/_layout/settings/notifications'
    | '/_protected/_layout/settings/profile'
    | '/_protected/_layout/settings/security'
    | '/_protected/_layout/system/audit-logs'
    | '/_protected/_layout/system/settings'
    | '/_protected/_layout/users/new'
    | '/_protected/_layout/roles/'
    | '/_protected/_layout/settings/'
    | '/_protected/_layout/users/'
    | '/_protected/_layout/s/$studioSlug/runners'
    | '/_protected/_layout/system/audit-logs/$id'
    | '/_protected/_layout/users/$id/edit'
    | '/_protected/_layout/s/$studioSlug/'
    | '/_protected/_layout/system/audit-logs/'
    | '/_protected/_layout/users/$id/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId'
    | '/_protected/_layout/s/$studioSlug/projects/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/content-types'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/contents'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/overview'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/repositories'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/structs'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/$pipelineId'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/$repositoryId'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/resources/$resourceId'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/contents/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/structs/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/new'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/new'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/structs/$structId/builder'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/'
    | '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_project': {
      id: '/_protected/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedProjectRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/_layout/': {
      id: '/_protected/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/403': {
      id: '/_protected/_layout/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof ProtectedLayout403RouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dev': {
      id: '/_protected/_layout/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof ProtectedLayoutDevRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/roles': {
      id: '/_protected/_layout/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof ProtectedLayoutRolesRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/runners': {
      id: '/_protected/_layout/runners'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof ProtectedLayoutRunnersRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/settings': {
      id: '/_protected/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedLayoutSettingsRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/users': {
      id: '/_protected/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedLayoutUsersRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/roles/': {
      id: '/_protected/_layout/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof ProtectedLayoutRolesIndexRouteImport
      parentRoute: typeof ProtectedLayoutRolesRouteRoute
    }
    '/_protected/_layout/settings/': {
      id: '/_protected/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedLayoutSettingsIndexRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/settings/notifications': {
      id: '/_protected/_layout/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedLayoutSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/settings/profile': {
      id: '/_protected/_layout/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedLayoutSettingsProfileRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/settings/security': {
      id: '/_protected/_layout/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof ProtectedLayoutSettingsSecurityRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/system/audit-logs': {
      id: '/_protected/_layout/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/system/audit-logs'
      preLoaderRoute: typeof ProtectedLayoutSystemAuditLogsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/system/settings': {
      id: '/_protected/_layout/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof ProtectedLayoutSystemSettingsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/users/': {
      id: '/_protected/_layout/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedLayoutUsersIndexRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_layout/users/new': {
      id: '/_protected/_layout/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof ProtectedLayoutUsersNewRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_layout/s/$studioSlug/': {
      id: '/_protected/_layout/s/$studioSlug/'
      path: '/s/$studioSlug'
      fullPath: '/s/$studioSlug/'
      preLoaderRoute: typeof ProtectedLayoutSStudioSlugIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/s/$studioSlug/runners': {
      id: '/_protected/_layout/s/$studioSlug/runners'
      path: '/s/$studioSlug/runners'
      fullPath: '/s/$studioSlug/runners'
      preLoaderRoute: typeof ProtectedLayoutSStudioSlugRunnersRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/system/audit-logs/': {
      id: '/_protected/_layout/system/audit-logs/'
      path: '/'
      fullPath: '/system/audit-logs/'
      preLoaderRoute: typeof ProtectedLayoutSystemAuditLogsIndexRouteImport
      parentRoute: typeof ProtectedLayoutSystemAuditLogsRoute
    }
    '/_protected/_layout/system/audit-logs/$id': {
      id: '/_protected/_layout/system/audit-logs/$id'
      path: '/$id'
      fullPath: '/system/audit-logs/$id'
      preLoaderRoute: typeof ProtectedLayoutSystemAuditLogsIdRouteImport
      parentRoute: typeof ProtectedLayoutSystemAuditLogsRoute
    }
    '/_protected/_layout/users/$id/': {
      id: '/_protected/_layout/users/$id/'
      path: '/$id'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof ProtectedLayoutUsersIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_layout/users/$id/edit': {
      id: '/_protected/_layout/users/$id/edit'
      path: '/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof ProtectedLayoutUsersIdEditRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_layout/s/$studioSlug/projects/': {
      id: '/_protected/_layout/s/$studioSlug/projects/'
      path: '/s/$studioSlug/projects'
      fullPath: '/s/$studioSlug/projects/'
      preLoaderRoute: typeof ProtectedLayoutSStudioSlugProjectsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId'
      path: '/s/$studioSlug/projects/$projectId'
      fullPath: '/s/$studioSlug/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteImport
      parentRoute: typeof ProtectedProjectRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/content-types': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/content-types'
      path: '/content-types'
      fullPath: '/s/$studioSlug/projects/$projectId/content-types'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/contents': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/contents'
      path: '/contents'
      fullPath: '/s/$studioSlug/projects/$projectId/contents'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/overview': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/s/$studioSlug/projects/$projectId/overview'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdOverviewRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/repositories': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/repositories'
      path: '/repositories'
      fullPath: '/s/$studioSlug/projects/$projectId/repositories'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/structs': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/structs'
      path: '/structs'
      fullPath: '/s/$studioSlug/projects/$projectId/structs'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/'
      path: '/'
      fullPath: '/s/$studioSlug/projects/$projectId/content-types/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/contents/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/contents/'
      path: '/'
      fullPath: '/s/$studioSlug/projects/$projectId/contents/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey'
      path: '/$typeKey'
      fullPath: '/s/$studioSlug/projects/$projectId/contents/$typeKey'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/'
      path: '/pipeline'
      fullPath: '/s/$studioSlug/projects/$projectId/pipeline/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/$pipelineId': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/$pipelineId'
      path: '/pipeline/$pipelineId'
      fullPath: '/s/$studioSlug/projects/$projectId/pipeline/$pipelineId'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/'
      path: '/'
      fullPath: '/s/$studioSlug/projects/$projectId/repositories/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/$repositoryId': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/repositories/$repositoryId'
      path: '/$repositoryId'
      fullPath: '/s/$studioSlug/projects/$projectId/repositories/$repositoryId'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/resources/$resourceId': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/s/$studioSlug/projects/$projectId/resources/$resourceId'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/structs/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/structs/'
      path: '/'
      fullPath: '/s/$studioSlug/projects/$projectId/structs/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/'
      path: '/$contentTypeId'
      fullPath: '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder'
      path: '/$contentTypeId/builder'
      fullPath: '/s/$studioSlug/projects/$projectId/content-types/$contentTypeId/builder'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/'
      path: '/'
      fullPath: '/s/$studioSlug/projects/$projectId/contents/$typeKey/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/new': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/new'
      path: '/new'
      fullPath: '/s/$studioSlug/projects/$projectId/contents/$typeKey/new'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/'
      path: '/pipeline/nodes'
      fullPath: '/s/$studioSlug/projects/$projectId/pipeline/nodes/'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest'
      path: '/pipeline/nodes/ingest'
      fullPath: '/s/$studioSlug/projects/$projectId/pipeline/nodes/ingest'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/new': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/pipeline/nodes/new'
      path: '/pipeline/nodes/new'
      fullPath: '/s/$studioSlug/projects/$projectId/pipeline/nodes/new'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/structs/$structId/builder': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/structs/$structId/builder'
      path: '/$structId/builder'
      fullPath: '/s/$studioSlug/projects/$projectId/structs/$structId/builder'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute
    }
    '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit': {
      id: '/_protected/_project/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit'
      path: '/$itemKey/edit'
      fullPath: '/s/$studioSlug/projects/$projectId/contents/$typeKey/$itemKey/edit'
      preLoaderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRouteImport
      parentRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute
    }
  }
}

interface ProtectedLayoutRolesRouteRouteChildren {
  ProtectedLayoutRolesIndexRoute: typeof ProtectedLayoutRolesIndexRoute
}

const ProtectedLayoutRolesRouteRouteChildren: ProtectedLayoutRolesRouteRouteChildren =
  {
    ProtectedLayoutRolesIndexRoute: ProtectedLayoutRolesIndexRoute,
  }

const ProtectedLayoutRolesRouteRouteWithChildren =
  ProtectedLayoutRolesRouteRoute._addFileChildren(
    ProtectedLayoutRolesRouteRouteChildren,
  )

interface ProtectedLayoutSettingsRouteRouteChildren {
  ProtectedLayoutSettingsNotificationsRoute: typeof ProtectedLayoutSettingsNotificationsRoute
  ProtectedLayoutSettingsProfileRoute: typeof ProtectedLayoutSettingsProfileRoute
  ProtectedLayoutSettingsSecurityRoute: typeof ProtectedLayoutSettingsSecurityRoute
  ProtectedLayoutSettingsIndexRoute: typeof ProtectedLayoutSettingsIndexRoute
}

const ProtectedLayoutSettingsRouteRouteChildren: ProtectedLayoutSettingsRouteRouteChildren =
  {
    ProtectedLayoutSettingsNotificationsRoute:
      ProtectedLayoutSettingsNotificationsRoute,
    ProtectedLayoutSettingsProfileRoute: ProtectedLayoutSettingsProfileRoute,
    ProtectedLayoutSettingsSecurityRoute: ProtectedLayoutSettingsSecurityRoute,
    ProtectedLayoutSettingsIndexRoute: ProtectedLayoutSettingsIndexRoute,
  }

const ProtectedLayoutSettingsRouteRouteWithChildren =
  ProtectedLayoutSettingsRouteRoute._addFileChildren(
    ProtectedLayoutSettingsRouteRouteChildren,
  )

interface ProtectedLayoutUsersRouteRouteChildren {
  ProtectedLayoutUsersNewRoute: typeof ProtectedLayoutUsersNewRoute
  ProtectedLayoutUsersIndexRoute: typeof ProtectedLayoutUsersIndexRoute
  ProtectedLayoutUsersIdEditRoute: typeof ProtectedLayoutUsersIdEditRoute
  ProtectedLayoutUsersIdIndexRoute: typeof ProtectedLayoutUsersIdIndexRoute
}

const ProtectedLayoutUsersRouteRouteChildren: ProtectedLayoutUsersRouteRouteChildren =
  {
    ProtectedLayoutUsersNewRoute: ProtectedLayoutUsersNewRoute,
    ProtectedLayoutUsersIndexRoute: ProtectedLayoutUsersIndexRoute,
    ProtectedLayoutUsersIdEditRoute: ProtectedLayoutUsersIdEditRoute,
    ProtectedLayoutUsersIdIndexRoute: ProtectedLayoutUsersIdIndexRoute,
  }

const ProtectedLayoutUsersRouteRouteWithChildren =
  ProtectedLayoutUsersRouteRoute._addFileChildren(
    ProtectedLayoutUsersRouteRouteChildren,
  )

interface ProtectedLayoutSystemAuditLogsRouteChildren {
  ProtectedLayoutSystemAuditLogsIdRoute: typeof ProtectedLayoutSystemAuditLogsIdRoute
  ProtectedLayoutSystemAuditLogsIndexRoute: typeof ProtectedLayoutSystemAuditLogsIndexRoute
}

const ProtectedLayoutSystemAuditLogsRouteChildren: ProtectedLayoutSystemAuditLogsRouteChildren =
  {
    ProtectedLayoutSystemAuditLogsIdRoute:
      ProtectedLayoutSystemAuditLogsIdRoute,
    ProtectedLayoutSystemAuditLogsIndexRoute:
      ProtectedLayoutSystemAuditLogsIndexRoute,
  }

const ProtectedLayoutSystemAuditLogsRouteWithChildren =
  ProtectedLayoutSystemAuditLogsRoute._addFileChildren(
    ProtectedLayoutSystemAuditLogsRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutRolesRouteRoute: typeof ProtectedLayoutRolesRouteRouteWithChildren
  ProtectedLayoutSettingsRouteRoute: typeof ProtectedLayoutSettingsRouteRouteWithChildren
  ProtectedLayoutUsersRouteRoute: typeof ProtectedLayoutUsersRouteRouteWithChildren
  ProtectedLayout403Route: typeof ProtectedLayout403Route
  ProtectedLayoutDevRoute: typeof ProtectedLayoutDevRoute
  ProtectedLayoutRunnersRoute: typeof ProtectedLayoutRunnersRoute
  ProtectedLayoutIndexRoute: typeof ProtectedLayoutIndexRoute
  ProtectedLayoutSystemAuditLogsRoute: typeof ProtectedLayoutSystemAuditLogsRouteWithChildren
  ProtectedLayoutSystemSettingsRoute: typeof ProtectedLayoutSystemSettingsRoute
  ProtectedLayoutSStudioSlugRunnersRoute: typeof ProtectedLayoutSStudioSlugRunnersRoute
  ProtectedLayoutSStudioSlugIndexRoute: typeof ProtectedLayoutSStudioSlugIndexRoute
  ProtectedLayoutSStudioSlugProjectsIndexRoute: typeof ProtectedLayoutSStudioSlugProjectsIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutRolesRouteRoute: ProtectedLayoutRolesRouteRouteWithChildren,
  ProtectedLayoutSettingsRouteRoute:
    ProtectedLayoutSettingsRouteRouteWithChildren,
  ProtectedLayoutUsersRouteRoute: ProtectedLayoutUsersRouteRouteWithChildren,
  ProtectedLayout403Route: ProtectedLayout403Route,
  ProtectedLayoutDevRoute: ProtectedLayoutDevRoute,
  ProtectedLayoutRunnersRoute: ProtectedLayoutRunnersRoute,
  ProtectedLayoutIndexRoute: ProtectedLayoutIndexRoute,
  ProtectedLayoutSystemAuditLogsRoute:
    ProtectedLayoutSystemAuditLogsRouteWithChildren,
  ProtectedLayoutSystemSettingsRoute: ProtectedLayoutSystemSettingsRoute,
  ProtectedLayoutSStudioSlugRunnersRoute:
    ProtectedLayoutSStudioSlugRunnersRoute,
  ProtectedLayoutSStudioSlugIndexRoute: ProtectedLayoutSStudioSlugIndexRoute,
  ProtectedLayoutSStudioSlugProjectsIndexRoute:
    ProtectedLayoutSStudioSlugProjectsIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteChildren {
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute
}

const ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteChildren: ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteChildren =
  {
    ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentTypesIndexRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdBuilderRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentTypesContentTypeIdIndexRoute,
  }

const ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteWithChildren =
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute._addFileChildren(
    ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteChildren,
  )

interface ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteChildren {
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute
}

const ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteChildren: ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteChildren =
  {
    ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyNewRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyIndexRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyItemKeyEditRoute,
  }

const ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteWithChildren =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute._addFileChildren(
    ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteChildren,
  )

interface ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteChildren {
  ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteWithChildren
  ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute
}

const ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteChildren: ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteChildren =
  {
    ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentsTypeKeyRouteWithChildren,
    ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentsIndexRoute,
  }

const ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteWithChildren =
  ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute._addFileChildren(
    ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteChildren,
  )

interface ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteChildren {
  ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute
  ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute
}

const ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteChildren: ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteChildren =
  {
    ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRepositoryIdRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesIndexRoute,
  }

const ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteWithChildren =
  ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute._addFileChildren(
    ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteChildren,
  )

interface ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteChildren {
  ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute
  ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute
}

const ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteChildren: ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteChildren =
  {
    ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdStructsIndexRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdStructsStructIdBuilderRoute,
  }

const ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteWithChildren =
  ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute._addFileChildren(
    ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteChildren,
  )

interface ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteChildren {
  ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteWithChildren
  ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteWithChildren
  ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute
  ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteWithChildren
  ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteWithChildren
  ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute
  ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute
  ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute
}

const ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteChildren: ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteChildren =
  {
    ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentTypesRouteWithChildren,
    ProtectedProjectSStudioSlugProjectsProjectIdContentsRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdContentsRouteWithChildren,
    ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdOverviewRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdRepositoriesRouteWithChildren,
    ProtectedProjectSStudioSlugProjectsProjectIdStructsRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdStructsRouteWithChildren,
    ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdPipelinePipelineIdRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdResourcesResourceIdRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdPipelineIndexRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIngestRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesNewRoute,
    ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute:
      ProtectedProjectSStudioSlugProjectsProjectIdPipelineNodesIndexRoute,
  }

const ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteWithChildren =
  ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute._addFileChildren(
    ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteChildren,
  )

interface ProtectedProjectRouteChildren {
  ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute: typeof ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteWithChildren
}

const ProtectedProjectRouteChildren: ProtectedProjectRouteChildren = {
  ProtectedProjectSStudioSlugProjectsProjectIdRouteRoute:
    ProtectedProjectSStudioSlugProjectsProjectIdRouteRouteWithChildren,
}

const ProtectedProjectRouteWithChildren =
  ProtectedProjectRoute._addFileChildren(ProtectedProjectRouteChildren)

interface ProtectedRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  ProtectedProjectRoute: typeof ProtectedProjectRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  ProtectedProjectRoute: ProtectedProjectRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
