/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/_layout'
import { Route as ProtectedProjectRouteImport } from './routes/_protected/_project'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth/accept-invite'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as ProtectedLayoutIndexRouteImport } from './routes/_protected/_layout/index'
import { Route as ProtectedLayout403RouteImport } from './routes/_protected/_layout/403'
import { Route as ProtectedLayoutDevRouteImport } from './routes/_protected/_layout/dev'
import { Route as ProtectedLayoutPlatformsRouteRouteImport } from './routes/_protected/_layout/platforms/route'
import { Route as ProtectedLayoutProjectsRouteRouteImport } from './routes/_protected/_layout/projects/route'
import { Route as ProtectedLayoutRolesRouteRouteImport } from './routes/_protected/_layout/roles/route'
import { Route as ProtectedLayoutRunnersRouteImport } from './routes/_protected/_layout/runners'
import { Route as ProtectedLayoutSettingsRouteRouteImport } from './routes/_protected/_layout/settings/route'
import { Route as ProtectedLayoutUsersRouteRouteImport } from './routes/_protected/_layout/users/route'
import { Route as ProtectedLayoutPlatformsIndexRouteImport } from './routes/_protected/_layout/platforms/index'
import { Route as ProtectedLayoutPlatformsExtensionsRouteImport } from './routes/_protected/_layout/platforms/extensions'
import { Route as ProtectedLayoutProjectsIndexRouteImport } from './routes/_protected/_layout/projects/index'
import { Route as ProtectedLayoutRolesIndexRouteImport } from './routes/_protected/_layout/roles/index'
import { Route as ProtectedLayoutSettingsIndexRouteImport } from './routes/_protected/_layout/settings/index'
import { Route as ProtectedLayoutSettingsNotificationsRouteImport } from './routes/_protected/_layout/settings/notifications'
import { Route as ProtectedLayoutSettingsProfileRouteImport } from './routes/_protected/_layout/settings/profile'
import { Route as ProtectedLayoutSettingsSecurityRouteImport } from './routes/_protected/_layout/settings/security'
import { Route as ProtectedLayoutSystemAuditLogsRouteImport } from './routes/_protected/_layout/system/audit-logs'
import { Route as ProtectedLayoutSystemSettingsRouteImport } from './routes/_protected/_layout/system/settings'
import { Route as ProtectedLayoutUsersIndexRouteImport } from './routes/_protected/_layout/users/index'
import { Route as ProtectedLayoutUsersNewRouteImport } from './routes/_protected/_layout/users/new'
import { Route as ProtectedProjectProjectsProjectIdRouteRouteImport } from './routes/_protected/_project/projects/$projectId/route'
import { Route as ProtectedLayoutSystemAuditLogsIndexRouteImport } from './routes/_protected/_layout/system/audit-logs/index'
import { Route as ProtectedLayoutSystemAuditLogsIdRouteImport } from './routes/_protected/_layout/system/audit-logs/$id'
import { Route as ProtectedLayoutUsersIdIndexRouteImport } from './routes/_protected/_layout/users/$id/index'
import { Route as ProtectedLayoutUsersIdEditRouteImport } from './routes/_protected/_layout/users/$id/edit'
import { Route as ProtectedProjectProjectsProjectIdContentTypesRouteImport } from './routes/_protected/_project/projects/$projectId/content-types'
import { Route as ProtectedProjectProjectsProjectIdContentsRouteImport } from './routes/_protected/_project/projects/$projectId/contents'
import { Route as ProtectedProjectProjectsProjectIdExecutorSettingsRouteImport } from './routes/_protected/_project/projects/$projectId/executor-settings'
import { Route as ProtectedProjectProjectsProjectIdOverviewRouteImport } from './routes/_protected/_project/projects/$projectId/overview'
import { Route as ProtectedProjectProjectsProjectIdRepositoriesRouteImport } from './routes/_protected/_project/projects/$projectId/repositories'
import { Route as ProtectedProjectProjectsProjectIdStructsRouteImport } from './routes/_protected/_project/projects/$projectId/structs'
import { Route as ProtectedProjectProjectsProjectIdContentTypesIndexRouteImport } from './routes/_protected/_project/projects/$projectId/content-types/index'
import { Route as ProtectedProjectProjectsProjectIdContentsIndexRouteImport } from './routes/_protected/_project/projects/$projectId/contents/index'
import { Route as ProtectedProjectProjectsProjectIdContentsTypeKeyRouteImport } from './routes/_protected/_project/projects/$projectId/contents/$typeKey'
import { Route as ProtectedProjectProjectsProjectIdPipelineIndexRouteImport } from './routes/_protected/_project/projects/$projectId/pipeline/index'
import { Route as ProtectedProjectProjectsProjectIdPipelinePipelineIdRouteImport } from './routes/_protected/_project/projects/$projectId/pipeline/$pipelineId'
import { Route as ProtectedProjectProjectsProjectIdRepositoriesIndexRouteImport } from './routes/_protected/_project/projects/$projectId/repositories/index'
import { Route as ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRouteImport } from './routes/_protected/_project/projects/$projectId/repositories/$repositoryId'
import { Route as ProtectedProjectProjectsProjectIdResourcesResourceIdRouteImport } from './routes/_protected/_project/projects/$projectId/resources/$resourceId'
import { Route as ProtectedProjectProjectsProjectIdStructsIndexRouteImport } from './routes/_protected/_project/projects/$projectId/structs/index'
import { Route as ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRouteImport } from './routes/_protected/_project/projects/$projectId/content-types/$contentTypeId/index'
import { Route as ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRouteImport } from './routes/_protected/_project/projects/$projectId/content-types/$contentTypeId/builder'
import { Route as ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRouteImport } from './routes/_protected/_project/projects/$projectId/contents/$typeKey/index'
import { Route as ProtectedProjectProjectsProjectIdContentsTypeKeyNewRouteImport } from './routes/_protected/_project/projects/$projectId/contents/$typeKey/new'
import { Route as ProtectedProjectProjectsProjectIdPipelineNodesIndexRouteImport } from './routes/_protected/_project/projects/$projectId/pipeline/nodes/index'
import { Route as ProtectedProjectProjectsProjectIdPipelineNodesNewRouteImport } from './routes/_protected/_project/projects/$projectId/pipeline/nodes/new'
import { Route as ProtectedProjectProjectsProjectIdStructsStructIdBuilderRouteImport } from './routes/_protected/_project/projects/$projectId/structs/$structId/builder'
import { Route as ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRouteImport } from './routes/_protected/_project/projects/$projectId/contents/$typeKey/$contentItemId/edit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProjectRoute = ProtectedProjectRouteImport.update({
  id: '/_project',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedLayoutIndexRoute = ProtectedLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayout403Route = ProtectedLayout403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutDevRoute = ProtectedLayoutDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutPlatformsRouteRoute =
  ProtectedLayoutPlatformsRouteRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutProjectsRouteRoute =
  ProtectedLayoutProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutRolesRouteRoute =
  ProtectedLayoutRolesRouteRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutRunnersRoute = ProtectedLayoutRunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutSettingsRouteRoute =
  ProtectedLayoutSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutUsersRouteRoute =
  ProtectedLayoutUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutPlatformsIndexRoute =
  ProtectedLayoutPlatformsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutPlatformsRouteRoute,
  } as any)
const ProtectedLayoutPlatformsExtensionsRoute =
  ProtectedLayoutPlatformsExtensionsRouteImport.update({
    id: '/extensions',
    path: '/extensions',
    getParentRoute: () => ProtectedLayoutPlatformsRouteRoute,
  } as any)
const ProtectedLayoutProjectsIndexRoute =
  ProtectedLayoutProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutProjectsRouteRoute,
  } as any)
const ProtectedLayoutRolesIndexRoute =
  ProtectedLayoutRolesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutRolesRouteRoute,
  } as any)
const ProtectedLayoutSettingsIndexRoute =
  ProtectedLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSettingsNotificationsRoute =
  ProtectedLayoutSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSettingsProfileRoute =
  ProtectedLayoutSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSettingsSecurityRoute =
  ProtectedLayoutSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedLayoutSettingsRouteRoute,
  } as any)
const ProtectedLayoutSystemAuditLogsRoute =
  ProtectedLayoutSystemAuditLogsRouteImport.update({
    id: '/system/audit-logs',
    path: '/system/audit-logs',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutSystemSettingsRoute =
  ProtectedLayoutSystemSettingsRouteImport.update({
    id: '/system/settings',
    path: '/system/settings',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutUsersIndexRoute =
  ProtectedLayoutUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutUsersRouteRoute,
  } as any)
const ProtectedLayoutUsersNewRoute = ProtectedLayoutUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedLayoutUsersRouteRoute,
} as any)
const ProtectedProjectProjectsProjectIdRouteRoute =
  ProtectedProjectProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProtectedProjectRoute,
  } as any)
const ProtectedLayoutSystemAuditLogsIndexRoute =
  ProtectedLayoutSystemAuditLogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedLayoutSystemAuditLogsRoute,
  } as any)
const ProtectedLayoutSystemAuditLogsIdRoute =
  ProtectedLayoutSystemAuditLogsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedLayoutSystemAuditLogsRoute,
  } as any)
const ProtectedLayoutUsersIdIndexRoute =
  ProtectedLayoutUsersIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => ProtectedLayoutUsersRouteRoute,
  } as any)
const ProtectedLayoutUsersIdEditRoute =
  ProtectedLayoutUsersIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => ProtectedLayoutUsersRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentTypesRoute =
  ProtectedProjectProjectsProjectIdContentTypesRouteImport.update({
    id: '/content-types',
    path: '/content-types',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentsRoute =
  ProtectedProjectProjectsProjectIdContentsRouteImport.update({
    id: '/contents',
    path: '/contents',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdExecutorSettingsRoute =
  ProtectedProjectProjectsProjectIdExecutorSettingsRouteImport.update({
    id: '/executor-settings',
    path: '/executor-settings',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdOverviewRoute =
  ProtectedProjectProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdRepositoriesRoute =
  ProtectedProjectProjectsProjectIdRepositoriesRouteImport.update({
    id: '/repositories',
    path: '/repositories',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdStructsRoute =
  ProtectedProjectProjectsProjectIdStructsRouteImport.update({
    id: '/structs',
    path: '/structs',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentTypesIndexRoute =
  ProtectedProjectProjectsProjectIdContentTypesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedProjectProjectsProjectIdContentTypesRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentsIndexRoute =
  ProtectedProjectProjectsProjectIdContentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedProjectProjectsProjectIdContentsRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentsTypeKeyRoute =
  ProtectedProjectProjectsProjectIdContentsTypeKeyRouteImport.update({
    id: '/$typeKey',
    path: '/$typeKey',
    getParentRoute: () => ProtectedProjectProjectsProjectIdContentsRoute,
  } as any)
const ProtectedProjectProjectsProjectIdPipelineIndexRoute =
  ProtectedProjectProjectsProjectIdPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute =
  ProtectedProjectProjectsProjectIdPipelinePipelineIdRouteImport.update({
    id: '/pipeline/$pipelineId',
    path: '/pipeline/$pipelineId',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdRepositoriesIndexRoute =
  ProtectedProjectProjectsProjectIdRepositoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRepositoriesRoute,
  } as any)
const ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute =
  ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRouteImport.update({
    id: '/$repositoryId',
    path: '/$repositoryId',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRepositoriesRoute,
  } as any)
const ProtectedProjectProjectsProjectIdResourcesResourceIdRoute =
  ProtectedProjectProjectsProjectIdResourcesResourceIdRouteImport.update({
    id: '/resources/$resourceId',
    path: '/resources/$resourceId',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdStructsIndexRoute =
  ProtectedProjectProjectsProjectIdStructsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedProjectProjectsProjectIdStructsRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute =
  ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRouteImport.update(
    {
      id: '/$contentTypeId/',
      path: '/$contentTypeId/',
      getParentRoute: () => ProtectedProjectProjectsProjectIdContentTypesRoute,
    } as any,
  )
const ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute =
  ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRouteImport.update(
    {
      id: '/$contentTypeId/builder',
      path: '/$contentTypeId/builder',
      getParentRoute: () => ProtectedProjectProjectsProjectIdContentTypesRoute,
    } as any,
  )
const ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute =
  ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedProjectProjectsProjectIdContentsTypeKeyRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute =
  ProtectedProjectProjectsProjectIdContentsTypeKeyNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedProjectProjectsProjectIdContentsTypeKeyRoute,
  } as any)
const ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute =
  ProtectedProjectProjectsProjectIdPipelineNodesIndexRouteImport.update({
    id: '/pipeline/nodes/',
    path: '/pipeline/nodes/',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdPipelineNodesNewRoute =
  ProtectedProjectProjectsProjectIdPipelineNodesNewRouteImport.update({
    id: '/pipeline/nodes/new',
    path: '/pipeline/nodes/new',
    getParentRoute: () => ProtectedProjectProjectsProjectIdRouteRoute,
  } as any)
const ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute =
  ProtectedProjectProjectsProjectIdStructsStructIdBuilderRouteImport.update({
    id: '/$structId/builder',
    path: '/$structId/builder',
    getParentRoute: () => ProtectedProjectProjectsProjectIdStructsRoute,
  } as any)
const ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute =
  ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRouteImport.update(
    {
      id: '/$contentItemId/edit',
      path: '/$contentItemId/edit',
      getParentRoute: () =>
        ProtectedProjectProjectsProjectIdContentsTypeKeyRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof ProtectedLayoutIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/platforms': typeof ProtectedLayoutPlatformsRouteRouteWithChildren
  '/projects': typeof ProtectedLayoutProjectsRouteRouteWithChildren
  '/roles': typeof ProtectedLayoutRolesRouteRouteWithChildren
  '/settings': typeof ProtectedLayoutSettingsRouteRouteWithChildren
  '/users': typeof ProtectedLayoutUsersRouteRouteWithChildren
  '/403': typeof ProtectedLayout403Route
  '/dev': typeof ProtectedLayoutDevRoute
  '/runners': typeof ProtectedLayoutRunnersRoute
  '/projects/$projectId': typeof ProtectedProjectProjectsProjectIdRouteRouteWithChildren
  '/platforms/extensions': typeof ProtectedLayoutPlatformsExtensionsRoute
  '/settings/notifications': typeof ProtectedLayoutSettingsNotificationsRoute
  '/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/settings/security': typeof ProtectedLayoutSettingsSecurityRoute
  '/system/audit-logs': typeof ProtectedLayoutSystemAuditLogsRouteWithChildren
  '/system/settings': typeof ProtectedLayoutSystemSettingsRoute
  '/users/new': typeof ProtectedLayoutUsersNewRoute
  '/platforms/': typeof ProtectedLayoutPlatformsIndexRoute
  '/projects/': typeof ProtectedLayoutProjectsIndexRoute
  '/roles/': typeof ProtectedLayoutRolesIndexRoute
  '/settings/': typeof ProtectedLayoutSettingsIndexRoute
  '/users/': typeof ProtectedLayoutUsersIndexRoute
  '/system/audit-logs/$id': typeof ProtectedLayoutSystemAuditLogsIdRoute
  '/users/$id/edit': typeof ProtectedLayoutUsersIdEditRoute
  '/projects/$projectId/content-types': typeof ProtectedProjectProjectsProjectIdContentTypesRouteWithChildren
  '/projects/$projectId/contents': typeof ProtectedProjectProjectsProjectIdContentsRouteWithChildren
  '/projects/$projectId/executor-settings': typeof ProtectedProjectProjectsProjectIdExecutorSettingsRoute
  '/projects/$projectId/overview': typeof ProtectedProjectProjectsProjectIdOverviewRoute
  '/projects/$projectId/repositories': typeof ProtectedProjectProjectsProjectIdRepositoriesRouteWithChildren
  '/projects/$projectId/structs': typeof ProtectedProjectProjectsProjectIdStructsRouteWithChildren
  '/system/audit-logs/': typeof ProtectedLayoutSystemAuditLogsIndexRoute
  '/users/$id/': typeof ProtectedLayoutUsersIdIndexRoute
  '/projects/$projectId/contents/$typeKey': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyRouteWithChildren
  '/projects/$projectId/pipeline/$pipelineId': typeof ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute
  '/projects/$projectId/repositories/$repositoryId': typeof ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute
  '/projects/$projectId/resources/$resourceId': typeof ProtectedProjectProjectsProjectIdResourcesResourceIdRoute
  '/projects/$projectId/content-types/': typeof ProtectedProjectProjectsProjectIdContentTypesIndexRoute
  '/projects/$projectId/contents/': typeof ProtectedProjectProjectsProjectIdContentsIndexRoute
  '/projects/$projectId/pipeline/': typeof ProtectedProjectProjectsProjectIdPipelineIndexRoute
  '/projects/$projectId/repositories/': typeof ProtectedProjectProjectsProjectIdRepositoriesIndexRoute
  '/projects/$projectId/structs/': typeof ProtectedProjectProjectsProjectIdStructsIndexRoute
  '/projects/$projectId/content-types/$contentTypeId/builder': typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  '/projects/$projectId/contents/$typeKey/new': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute
  '/projects/$projectId/pipeline/nodes/new': typeof ProtectedProjectProjectsProjectIdPipelineNodesNewRoute
  '/projects/$projectId/structs/$structId/builder': typeof ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute
  '/projects/$projectId/content-types/$contentTypeId/': typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute
  '/projects/$projectId/contents/$typeKey/': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute
  '/projects/$projectId/pipeline/nodes/': typeof ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute
  '/projects/$projectId/contents/$typeKey/$contentItemId/edit': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedLayoutIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/403': typeof ProtectedLayout403Route
  '/dev': typeof ProtectedLayoutDevRoute
  '/runners': typeof ProtectedLayoutRunnersRoute
  '/projects/$projectId': typeof ProtectedProjectProjectsProjectIdRouteRouteWithChildren
  '/platforms/extensions': typeof ProtectedLayoutPlatformsExtensionsRoute
  '/settings/notifications': typeof ProtectedLayoutSettingsNotificationsRoute
  '/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/settings/security': typeof ProtectedLayoutSettingsSecurityRoute
  '/system/settings': typeof ProtectedLayoutSystemSettingsRoute
  '/users/new': typeof ProtectedLayoutUsersNewRoute
  '/platforms': typeof ProtectedLayoutPlatformsIndexRoute
  '/projects': typeof ProtectedLayoutProjectsIndexRoute
  '/roles': typeof ProtectedLayoutRolesIndexRoute
  '/settings': typeof ProtectedLayoutSettingsIndexRoute
  '/users': typeof ProtectedLayoutUsersIndexRoute
  '/system/audit-logs/$id': typeof ProtectedLayoutSystemAuditLogsIdRoute
  '/users/$id/edit': typeof ProtectedLayoutUsersIdEditRoute
  '/projects/$projectId/executor-settings': typeof ProtectedProjectProjectsProjectIdExecutorSettingsRoute
  '/projects/$projectId/overview': typeof ProtectedProjectProjectsProjectIdOverviewRoute
  '/system/audit-logs': typeof ProtectedLayoutSystemAuditLogsIndexRoute
  '/users/$id': typeof ProtectedLayoutUsersIdIndexRoute
  '/projects/$projectId/pipeline/$pipelineId': typeof ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute
  '/projects/$projectId/repositories/$repositoryId': typeof ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute
  '/projects/$projectId/resources/$resourceId': typeof ProtectedProjectProjectsProjectIdResourcesResourceIdRoute
  '/projects/$projectId/content-types': typeof ProtectedProjectProjectsProjectIdContentTypesIndexRoute
  '/projects/$projectId/contents': typeof ProtectedProjectProjectsProjectIdContentsIndexRoute
  '/projects/$projectId/pipeline': typeof ProtectedProjectProjectsProjectIdPipelineIndexRoute
  '/projects/$projectId/repositories': typeof ProtectedProjectProjectsProjectIdRepositoriesIndexRoute
  '/projects/$projectId/structs': typeof ProtectedProjectProjectsProjectIdStructsIndexRoute
  '/projects/$projectId/content-types/$contentTypeId/builder': typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  '/projects/$projectId/contents/$typeKey/new': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute
  '/projects/$projectId/pipeline/nodes/new': typeof ProtectedProjectProjectsProjectIdPipelineNodesNewRoute
  '/projects/$projectId/structs/$structId/builder': typeof ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute
  '/projects/$projectId/content-types/$contentTypeId': typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute
  '/projects/$projectId/contents/$typeKey': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute
  '/projects/$projectId/pipeline/nodes': typeof ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute
  '/projects/$projectId/contents/$typeKey/$contentItemId/edit': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/_protected/_project': typeof ProtectedProjectRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_protected/_layout/platforms': typeof ProtectedLayoutPlatformsRouteRouteWithChildren
  '/_protected/_layout/projects': typeof ProtectedLayoutProjectsRouteRouteWithChildren
  '/_protected/_layout/roles': typeof ProtectedLayoutRolesRouteRouteWithChildren
  '/_protected/_layout/settings': typeof ProtectedLayoutSettingsRouteRouteWithChildren
  '/_protected/_layout/users': typeof ProtectedLayoutUsersRouteRouteWithChildren
  '/_protected/_layout/403': typeof ProtectedLayout403Route
  '/_protected/_layout/dev': typeof ProtectedLayoutDevRoute
  '/_protected/_layout/runners': typeof ProtectedLayoutRunnersRoute
  '/_protected/_layout/': typeof ProtectedLayoutIndexRoute
  '/_protected/_project/projects/$projectId': typeof ProtectedProjectProjectsProjectIdRouteRouteWithChildren
  '/_protected/_layout/platforms/extensions': typeof ProtectedLayoutPlatformsExtensionsRoute
  '/_protected/_layout/settings/notifications': typeof ProtectedLayoutSettingsNotificationsRoute
  '/_protected/_layout/settings/profile': typeof ProtectedLayoutSettingsProfileRoute
  '/_protected/_layout/settings/security': typeof ProtectedLayoutSettingsSecurityRoute
  '/_protected/_layout/system/audit-logs': typeof ProtectedLayoutSystemAuditLogsRouteWithChildren
  '/_protected/_layout/system/settings': typeof ProtectedLayoutSystemSettingsRoute
  '/_protected/_layout/users/new': typeof ProtectedLayoutUsersNewRoute
  '/_protected/_layout/platforms/': typeof ProtectedLayoutPlatformsIndexRoute
  '/_protected/_layout/projects/': typeof ProtectedLayoutProjectsIndexRoute
  '/_protected/_layout/roles/': typeof ProtectedLayoutRolesIndexRoute
  '/_protected/_layout/settings/': typeof ProtectedLayoutSettingsIndexRoute
  '/_protected/_layout/users/': typeof ProtectedLayoutUsersIndexRoute
  '/_protected/_layout/system/audit-logs/$id': typeof ProtectedLayoutSystemAuditLogsIdRoute
  '/_protected/_layout/users/$id/edit': typeof ProtectedLayoutUsersIdEditRoute
  '/_protected/_project/projects/$projectId/content-types': typeof ProtectedProjectProjectsProjectIdContentTypesRouteWithChildren
  '/_protected/_project/projects/$projectId/contents': typeof ProtectedProjectProjectsProjectIdContentsRouteWithChildren
  '/_protected/_project/projects/$projectId/executor-settings': typeof ProtectedProjectProjectsProjectIdExecutorSettingsRoute
  '/_protected/_project/projects/$projectId/overview': typeof ProtectedProjectProjectsProjectIdOverviewRoute
  '/_protected/_project/projects/$projectId/repositories': typeof ProtectedProjectProjectsProjectIdRepositoriesRouteWithChildren
  '/_protected/_project/projects/$projectId/structs': typeof ProtectedProjectProjectsProjectIdStructsRouteWithChildren
  '/_protected/_layout/system/audit-logs/': typeof ProtectedLayoutSystemAuditLogsIndexRoute
  '/_protected/_layout/users/$id/': typeof ProtectedLayoutUsersIdIndexRoute
  '/_protected/_project/projects/$projectId/contents/$typeKey': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyRouteWithChildren
  '/_protected/_project/projects/$projectId/pipeline/$pipelineId': typeof ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute
  '/_protected/_project/projects/$projectId/repositories/$repositoryId': typeof ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute
  '/_protected/_project/projects/$projectId/resources/$resourceId': typeof ProtectedProjectProjectsProjectIdResourcesResourceIdRoute
  '/_protected/_project/projects/$projectId/content-types/': typeof ProtectedProjectProjectsProjectIdContentTypesIndexRoute
  '/_protected/_project/projects/$projectId/contents/': typeof ProtectedProjectProjectsProjectIdContentsIndexRoute
  '/_protected/_project/projects/$projectId/pipeline/': typeof ProtectedProjectProjectsProjectIdPipelineIndexRoute
  '/_protected/_project/projects/$projectId/repositories/': typeof ProtectedProjectProjectsProjectIdRepositoriesIndexRoute
  '/_protected/_project/projects/$projectId/structs/': typeof ProtectedProjectProjectsProjectIdStructsIndexRoute
  '/_protected/_project/projects/$projectId/content-types/$contentTypeId/builder': typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  '/_protected/_project/projects/$projectId/contents/$typeKey/new': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute
  '/_protected/_project/projects/$projectId/pipeline/nodes/new': typeof ProtectedProjectProjectsProjectIdPipelineNodesNewRoute
  '/_protected/_project/projects/$projectId/structs/$structId/builder': typeof ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute
  '/_protected/_project/projects/$projectId/content-types/$contentTypeId/': typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute
  '/_protected/_project/projects/$projectId/contents/$typeKey/': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute
  '/_protected/_project/projects/$projectId/pipeline/nodes/': typeof ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute
  '/_protected/_project/projects/$projectId/contents/$typeKey/$contentItemId/edit': typeof ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/platforms'
    | '/projects'
    | '/roles'
    | '/settings'
    | '/users'
    | '/403'
    | '/dev'
    | '/runners'
    | '/projects/$projectId'
    | '/platforms/extensions'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/system/audit-logs'
    | '/system/settings'
    | '/users/new'
    | '/platforms/'
    | '/projects/'
    | '/roles/'
    | '/settings/'
    | '/users/'
    | '/system/audit-logs/$id'
    | '/users/$id/edit'
    | '/projects/$projectId/content-types'
    | '/projects/$projectId/contents'
    | '/projects/$projectId/executor-settings'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/repositories'
    | '/projects/$projectId/structs'
    | '/system/audit-logs/'
    | '/users/$id/'
    | '/projects/$projectId/contents/$typeKey'
    | '/projects/$projectId/pipeline/$pipelineId'
    | '/projects/$projectId/repositories/$repositoryId'
    | '/projects/$projectId/resources/$resourceId'
    | '/projects/$projectId/content-types/'
    | '/projects/$projectId/contents/'
    | '/projects/$projectId/pipeline/'
    | '/projects/$projectId/repositories/'
    | '/projects/$projectId/structs/'
    | '/projects/$projectId/content-types/$contentTypeId/builder'
    | '/projects/$projectId/contents/$typeKey/new'
    | '/projects/$projectId/pipeline/nodes/new'
    | '/projects/$projectId/structs/$structId/builder'
    | '/projects/$projectId/content-types/$contentTypeId/'
    | '/projects/$projectId/contents/$typeKey/'
    | '/projects/$projectId/pipeline/nodes/'
    | '/projects/$projectId/contents/$typeKey/$contentItemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/403'
    | '/dev'
    | '/runners'
    | '/projects/$projectId'
    | '/platforms/extensions'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/system/settings'
    | '/users/new'
    | '/platforms'
    | '/projects'
    | '/roles'
    | '/settings'
    | '/users'
    | '/system/audit-logs/$id'
    | '/users/$id/edit'
    | '/projects/$projectId/executor-settings'
    | '/projects/$projectId/overview'
    | '/system/audit-logs'
    | '/users/$id'
    | '/projects/$projectId/pipeline/$pipelineId'
    | '/projects/$projectId/repositories/$repositoryId'
    | '/projects/$projectId/resources/$resourceId'
    | '/projects/$projectId/content-types'
    | '/projects/$projectId/contents'
    | '/projects/$projectId/pipeline'
    | '/projects/$projectId/repositories'
    | '/projects/$projectId/structs'
    | '/projects/$projectId/content-types/$contentTypeId/builder'
    | '/projects/$projectId/contents/$typeKey/new'
    | '/projects/$projectId/pipeline/nodes/new'
    | '/projects/$projectId/structs/$structId/builder'
    | '/projects/$projectId/content-types/$contentTypeId'
    | '/projects/$projectId/contents/$typeKey'
    | '/projects/$projectId/pipeline/nodes'
    | '/projects/$projectId/contents/$typeKey/$contentItemId/edit'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/_layout'
    | '/_protected/_project'
    | '/_protected/onboarding'
    | '/auth/accept-invite'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/reset-password'
    | '/_protected/_layout/platforms'
    | '/_protected/_layout/projects'
    | '/_protected/_layout/roles'
    | '/_protected/_layout/settings'
    | '/_protected/_layout/users'
    | '/_protected/_layout/403'
    | '/_protected/_layout/dev'
    | '/_protected/_layout/runners'
    | '/_protected/_layout/'
    | '/_protected/_project/projects/$projectId'
    | '/_protected/_layout/platforms/extensions'
    | '/_protected/_layout/settings/notifications'
    | '/_protected/_layout/settings/profile'
    | '/_protected/_layout/settings/security'
    | '/_protected/_layout/system/audit-logs'
    | '/_protected/_layout/system/settings'
    | '/_protected/_layout/users/new'
    | '/_protected/_layout/platforms/'
    | '/_protected/_layout/projects/'
    | '/_protected/_layout/roles/'
    | '/_protected/_layout/settings/'
    | '/_protected/_layout/users/'
    | '/_protected/_layout/system/audit-logs/$id'
    | '/_protected/_layout/users/$id/edit'
    | '/_protected/_project/projects/$projectId/content-types'
    | '/_protected/_project/projects/$projectId/contents'
    | '/_protected/_project/projects/$projectId/executor-settings'
    | '/_protected/_project/projects/$projectId/overview'
    | '/_protected/_project/projects/$projectId/repositories'
    | '/_protected/_project/projects/$projectId/structs'
    | '/_protected/_layout/system/audit-logs/'
    | '/_protected/_layout/users/$id/'
    | '/_protected/_project/projects/$projectId/contents/$typeKey'
    | '/_protected/_project/projects/$projectId/pipeline/$pipelineId'
    | '/_protected/_project/projects/$projectId/repositories/$repositoryId'
    | '/_protected/_project/projects/$projectId/resources/$resourceId'
    | '/_protected/_project/projects/$projectId/content-types/'
    | '/_protected/_project/projects/$projectId/contents/'
    | '/_protected/_project/projects/$projectId/pipeline/'
    | '/_protected/_project/projects/$projectId/repositories/'
    | '/_protected/_project/projects/$projectId/structs/'
    | '/_protected/_project/projects/$projectId/content-types/$contentTypeId/builder'
    | '/_protected/_project/projects/$projectId/contents/$typeKey/new'
    | '/_protected/_project/projects/$projectId/pipeline/nodes/new'
    | '/_protected/_project/projects/$projectId/structs/$structId/builder'
    | '/_protected/_project/projects/$projectId/content-types/$contentTypeId/'
    | '/_protected/_project/projects/$projectId/contents/$typeKey/'
    | '/_protected/_project/projects/$projectId/pipeline/nodes/'
    | '/_protected/_project/projects/$projectId/contents/$typeKey/$contentItemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_project': {
      id: '/_protected/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedProjectRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/_layout/': {
      id: '/_protected/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/403': {
      id: '/_protected/_layout/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof ProtectedLayout403RouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dev': {
      id: '/_protected/_layout/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof ProtectedLayoutDevRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/platforms': {
      id: '/_protected/_layout/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof ProtectedLayoutPlatformsRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/projects': {
      id: '/_protected/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedLayoutProjectsRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/roles': {
      id: '/_protected/_layout/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof ProtectedLayoutRolesRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/runners': {
      id: '/_protected/_layout/runners'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof ProtectedLayoutRunnersRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/settings': {
      id: '/_protected/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedLayoutSettingsRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/users': {
      id: '/_protected/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedLayoutUsersRouteRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/platforms/': {
      id: '/_protected/_layout/platforms/'
      path: '/'
      fullPath: '/platforms/'
      preLoaderRoute: typeof ProtectedLayoutPlatformsIndexRouteImport
      parentRoute: typeof ProtectedLayoutPlatformsRouteRoute
    }
    '/_protected/_layout/platforms/extensions': {
      id: '/_protected/_layout/platforms/extensions'
      path: '/extensions'
      fullPath: '/platforms/extensions'
      preLoaderRoute: typeof ProtectedLayoutPlatformsExtensionsRouteImport
      parentRoute: typeof ProtectedLayoutPlatformsRouteRoute
    }
    '/_protected/_layout/projects/': {
      id: '/_protected/_layout/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProtectedLayoutProjectsIndexRouteImport
      parentRoute: typeof ProtectedLayoutProjectsRouteRoute
    }
    '/_protected/_layout/roles/': {
      id: '/_protected/_layout/roles/'
      path: '/'
      fullPath: '/roles/'
      preLoaderRoute: typeof ProtectedLayoutRolesIndexRouteImport
      parentRoute: typeof ProtectedLayoutRolesRouteRoute
    }
    '/_protected/_layout/settings/': {
      id: '/_protected/_layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedLayoutSettingsIndexRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/settings/notifications': {
      id: '/_protected/_layout/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedLayoutSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/settings/profile': {
      id: '/_protected/_layout/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedLayoutSettingsProfileRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/settings/security': {
      id: '/_protected/_layout/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof ProtectedLayoutSettingsSecurityRouteImport
      parentRoute: typeof ProtectedLayoutSettingsRouteRoute
    }
    '/_protected/_layout/system/audit-logs': {
      id: '/_protected/_layout/system/audit-logs'
      path: '/system/audit-logs'
      fullPath: '/system/audit-logs'
      preLoaderRoute: typeof ProtectedLayoutSystemAuditLogsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/system/settings': {
      id: '/_protected/_layout/system/settings'
      path: '/system/settings'
      fullPath: '/system/settings'
      preLoaderRoute: typeof ProtectedLayoutSystemSettingsRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/users/': {
      id: '/_protected/_layout/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedLayoutUsersIndexRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_layout/users/new': {
      id: '/_protected/_layout/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof ProtectedLayoutUsersNewRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_project/projects/$projectId': {
      id: '/_protected/_project/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdRouteRouteImport
      parentRoute: typeof ProtectedProjectRoute
    }
    '/_protected/_layout/system/audit-logs/': {
      id: '/_protected/_layout/system/audit-logs/'
      path: '/'
      fullPath: '/system/audit-logs/'
      preLoaderRoute: typeof ProtectedLayoutSystemAuditLogsIndexRouteImport
      parentRoute: typeof ProtectedLayoutSystemAuditLogsRoute
    }
    '/_protected/_layout/system/audit-logs/$id': {
      id: '/_protected/_layout/system/audit-logs/$id'
      path: '/$id'
      fullPath: '/system/audit-logs/$id'
      preLoaderRoute: typeof ProtectedLayoutSystemAuditLogsIdRouteImport
      parentRoute: typeof ProtectedLayoutSystemAuditLogsRoute
    }
    '/_protected/_layout/users/$id/': {
      id: '/_protected/_layout/users/$id/'
      path: '/$id'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof ProtectedLayoutUsersIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_layout/users/$id/edit': {
      id: '/_protected/_layout/users/$id/edit'
      path: '/$id/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof ProtectedLayoutUsersIdEditRouteImport
      parentRoute: typeof ProtectedLayoutUsersRouteRoute
    }
    '/_protected/_project/projects/$projectId/content-types': {
      id: '/_protected/_project/projects/$projectId/content-types'
      path: '/content-types'
      fullPath: '/projects/$projectId/content-types'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentTypesRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/contents': {
      id: '/_protected/_project/projects/$projectId/contents'
      path: '/contents'
      fullPath: '/projects/$projectId/contents'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentsRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/executor-settings': {
      id: '/_protected/_project/projects/$projectId/executor-settings'
      path: '/executor-settings'
      fullPath: '/projects/$projectId/executor-settings'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdExecutorSettingsRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/overview': {
      id: '/_protected/_project/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdOverviewRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/repositories': {
      id: '/_protected/_project/projects/$projectId/repositories'
      path: '/repositories'
      fullPath: '/projects/$projectId/repositories'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/structs': {
      id: '/_protected/_project/projects/$projectId/structs'
      path: '/structs'
      fullPath: '/projects/$projectId/structs'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdStructsRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/content-types/': {
      id: '/_protected/_project/projects/$projectId/content-types/'
      path: '/'
      fullPath: '/projects/$projectId/content-types/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentTypesIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentTypesRoute
    }
    '/_protected/_project/projects/$projectId/contents/': {
      id: '/_protected/_project/projects/$projectId/contents/'
      path: '/'
      fullPath: '/projects/$projectId/contents/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentsIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentsRoute
    }
    '/_protected/_project/projects/$projectId/contents/$typeKey': {
      id: '/_protected/_project/projects/$projectId/contents/$typeKey'
      path: '/$typeKey'
      fullPath: '/projects/$projectId/contents/$typeKey'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentsRoute
    }
    '/_protected/_project/projects/$projectId/pipeline/': {
      id: '/_protected/_project/projects/$projectId/pipeline/'
      path: '/pipeline'
      fullPath: '/projects/$projectId/pipeline/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdPipelineIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/pipeline/$pipelineId': {
      id: '/_protected/_project/projects/$projectId/pipeline/$pipelineId'
      path: '/pipeline/$pipelineId'
      fullPath: '/projects/$projectId/pipeline/$pipelineId'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdPipelinePipelineIdRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/repositories/': {
      id: '/_protected/_project/projects/$projectId/repositories/'
      path: '/'
      fullPath: '/projects/$projectId/repositories/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesRoute
    }
    '/_protected/_project/projects/$projectId/repositories/$repositoryId': {
      id: '/_protected/_project/projects/$projectId/repositories/$repositoryId'
      path: '/$repositoryId'
      fullPath: '/projects/$projectId/repositories/$repositoryId'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesRoute
    }
    '/_protected/_project/projects/$projectId/resources/$resourceId': {
      id: '/_protected/_project/projects/$projectId/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/projects/$projectId/resources/$resourceId'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdResourcesResourceIdRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/structs/': {
      id: '/_protected/_project/projects/$projectId/structs/'
      path: '/'
      fullPath: '/projects/$projectId/structs/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdStructsIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdStructsRoute
    }
    '/_protected/_project/projects/$projectId/content-types/$contentTypeId/': {
      id: '/_protected/_project/projects/$projectId/content-types/$contentTypeId/'
      path: '/$contentTypeId'
      fullPath: '/projects/$projectId/content-types/$contentTypeId/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentTypesRoute
    }
    '/_protected/_project/projects/$projectId/content-types/$contentTypeId/builder': {
      id: '/_protected/_project/projects/$projectId/content-types/$contentTypeId/builder'
      path: '/$contentTypeId/builder'
      fullPath: '/projects/$projectId/content-types/$contentTypeId/builder'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentTypesRoute
    }
    '/_protected/_project/projects/$projectId/contents/$typeKey/': {
      id: '/_protected/_project/projects/$projectId/contents/$typeKey/'
      path: '/'
      fullPath: '/projects/$projectId/contents/$typeKey/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyRoute
    }
    '/_protected/_project/projects/$projectId/contents/$typeKey/new': {
      id: '/_protected/_project/projects/$projectId/contents/$typeKey/new'
      path: '/new'
      fullPath: '/projects/$projectId/contents/$typeKey/new'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyNewRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyRoute
    }
    '/_protected/_project/projects/$projectId/pipeline/nodes/': {
      id: '/_protected/_project/projects/$projectId/pipeline/nodes/'
      path: '/pipeline/nodes'
      fullPath: '/projects/$projectId/pipeline/nodes/'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdPipelineNodesIndexRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/pipeline/nodes/new': {
      id: '/_protected/_project/projects/$projectId/pipeline/nodes/new'
      path: '/pipeline/nodes/new'
      fullPath: '/projects/$projectId/pipeline/nodes/new'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdPipelineNodesNewRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdRouteRoute
    }
    '/_protected/_project/projects/$projectId/structs/$structId/builder': {
      id: '/_protected/_project/projects/$projectId/structs/$structId/builder'
      path: '/$structId/builder'
      fullPath: '/projects/$projectId/structs/$structId/builder'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdStructsStructIdBuilderRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdStructsRoute
    }
    '/_protected/_project/projects/$projectId/contents/$typeKey/$contentItemId/edit': {
      id: '/_protected/_project/projects/$projectId/contents/$typeKey/$contentItemId/edit'
      path: '/$contentItemId/edit'
      fullPath: '/projects/$projectId/contents/$typeKey/$contentItemId/edit'
      preLoaderRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRouteImport
      parentRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyRoute
    }
  }
}

interface ProtectedLayoutPlatformsRouteRouteChildren {
  ProtectedLayoutPlatformsExtensionsRoute: typeof ProtectedLayoutPlatformsExtensionsRoute
  ProtectedLayoutPlatformsIndexRoute: typeof ProtectedLayoutPlatformsIndexRoute
}

const ProtectedLayoutPlatformsRouteRouteChildren: ProtectedLayoutPlatformsRouteRouteChildren =
  {
    ProtectedLayoutPlatformsExtensionsRoute:
      ProtectedLayoutPlatformsExtensionsRoute,
    ProtectedLayoutPlatformsIndexRoute: ProtectedLayoutPlatformsIndexRoute,
  }

const ProtectedLayoutPlatformsRouteRouteWithChildren =
  ProtectedLayoutPlatformsRouteRoute._addFileChildren(
    ProtectedLayoutPlatformsRouteRouteChildren,
  )

interface ProtectedLayoutProjectsRouteRouteChildren {
  ProtectedLayoutProjectsIndexRoute: typeof ProtectedLayoutProjectsIndexRoute
}

const ProtectedLayoutProjectsRouteRouteChildren: ProtectedLayoutProjectsRouteRouteChildren =
  {
    ProtectedLayoutProjectsIndexRoute: ProtectedLayoutProjectsIndexRoute,
  }

const ProtectedLayoutProjectsRouteRouteWithChildren =
  ProtectedLayoutProjectsRouteRoute._addFileChildren(
    ProtectedLayoutProjectsRouteRouteChildren,
  )

interface ProtectedLayoutRolesRouteRouteChildren {
  ProtectedLayoutRolesIndexRoute: typeof ProtectedLayoutRolesIndexRoute
}

const ProtectedLayoutRolesRouteRouteChildren: ProtectedLayoutRolesRouteRouteChildren =
  {
    ProtectedLayoutRolesIndexRoute: ProtectedLayoutRolesIndexRoute,
  }

const ProtectedLayoutRolesRouteRouteWithChildren =
  ProtectedLayoutRolesRouteRoute._addFileChildren(
    ProtectedLayoutRolesRouteRouteChildren,
  )

interface ProtectedLayoutSettingsRouteRouteChildren {
  ProtectedLayoutSettingsNotificationsRoute: typeof ProtectedLayoutSettingsNotificationsRoute
  ProtectedLayoutSettingsProfileRoute: typeof ProtectedLayoutSettingsProfileRoute
  ProtectedLayoutSettingsSecurityRoute: typeof ProtectedLayoutSettingsSecurityRoute
  ProtectedLayoutSettingsIndexRoute: typeof ProtectedLayoutSettingsIndexRoute
}

const ProtectedLayoutSettingsRouteRouteChildren: ProtectedLayoutSettingsRouteRouteChildren =
  {
    ProtectedLayoutSettingsNotificationsRoute:
      ProtectedLayoutSettingsNotificationsRoute,
    ProtectedLayoutSettingsProfileRoute: ProtectedLayoutSettingsProfileRoute,
    ProtectedLayoutSettingsSecurityRoute: ProtectedLayoutSettingsSecurityRoute,
    ProtectedLayoutSettingsIndexRoute: ProtectedLayoutSettingsIndexRoute,
  }

const ProtectedLayoutSettingsRouteRouteWithChildren =
  ProtectedLayoutSettingsRouteRoute._addFileChildren(
    ProtectedLayoutSettingsRouteRouteChildren,
  )

interface ProtectedLayoutUsersRouteRouteChildren {
  ProtectedLayoutUsersNewRoute: typeof ProtectedLayoutUsersNewRoute
  ProtectedLayoutUsersIndexRoute: typeof ProtectedLayoutUsersIndexRoute
  ProtectedLayoutUsersIdEditRoute: typeof ProtectedLayoutUsersIdEditRoute
  ProtectedLayoutUsersIdIndexRoute: typeof ProtectedLayoutUsersIdIndexRoute
}

const ProtectedLayoutUsersRouteRouteChildren: ProtectedLayoutUsersRouteRouteChildren =
  {
    ProtectedLayoutUsersNewRoute: ProtectedLayoutUsersNewRoute,
    ProtectedLayoutUsersIndexRoute: ProtectedLayoutUsersIndexRoute,
    ProtectedLayoutUsersIdEditRoute: ProtectedLayoutUsersIdEditRoute,
    ProtectedLayoutUsersIdIndexRoute: ProtectedLayoutUsersIdIndexRoute,
  }

const ProtectedLayoutUsersRouteRouteWithChildren =
  ProtectedLayoutUsersRouteRoute._addFileChildren(
    ProtectedLayoutUsersRouteRouteChildren,
  )

interface ProtectedLayoutSystemAuditLogsRouteChildren {
  ProtectedLayoutSystemAuditLogsIdRoute: typeof ProtectedLayoutSystemAuditLogsIdRoute
  ProtectedLayoutSystemAuditLogsIndexRoute: typeof ProtectedLayoutSystemAuditLogsIndexRoute
}

const ProtectedLayoutSystemAuditLogsRouteChildren: ProtectedLayoutSystemAuditLogsRouteChildren =
  {
    ProtectedLayoutSystemAuditLogsIdRoute:
      ProtectedLayoutSystemAuditLogsIdRoute,
    ProtectedLayoutSystemAuditLogsIndexRoute:
      ProtectedLayoutSystemAuditLogsIndexRoute,
  }

const ProtectedLayoutSystemAuditLogsRouteWithChildren =
  ProtectedLayoutSystemAuditLogsRoute._addFileChildren(
    ProtectedLayoutSystemAuditLogsRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutPlatformsRouteRoute: typeof ProtectedLayoutPlatformsRouteRouteWithChildren
  ProtectedLayoutProjectsRouteRoute: typeof ProtectedLayoutProjectsRouteRouteWithChildren
  ProtectedLayoutRolesRouteRoute: typeof ProtectedLayoutRolesRouteRouteWithChildren
  ProtectedLayoutSettingsRouteRoute: typeof ProtectedLayoutSettingsRouteRouteWithChildren
  ProtectedLayoutUsersRouteRoute: typeof ProtectedLayoutUsersRouteRouteWithChildren
  ProtectedLayout403Route: typeof ProtectedLayout403Route
  ProtectedLayoutDevRoute: typeof ProtectedLayoutDevRoute
  ProtectedLayoutRunnersRoute: typeof ProtectedLayoutRunnersRoute
  ProtectedLayoutIndexRoute: typeof ProtectedLayoutIndexRoute
  ProtectedLayoutSystemAuditLogsRoute: typeof ProtectedLayoutSystemAuditLogsRouteWithChildren
  ProtectedLayoutSystemSettingsRoute: typeof ProtectedLayoutSystemSettingsRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutPlatformsRouteRoute:
    ProtectedLayoutPlatformsRouteRouteWithChildren,
  ProtectedLayoutProjectsRouteRoute:
    ProtectedLayoutProjectsRouteRouteWithChildren,
  ProtectedLayoutRolesRouteRoute: ProtectedLayoutRolesRouteRouteWithChildren,
  ProtectedLayoutSettingsRouteRoute:
    ProtectedLayoutSettingsRouteRouteWithChildren,
  ProtectedLayoutUsersRouteRoute: ProtectedLayoutUsersRouteRouteWithChildren,
  ProtectedLayout403Route: ProtectedLayout403Route,
  ProtectedLayoutDevRoute: ProtectedLayoutDevRoute,
  ProtectedLayoutRunnersRoute: ProtectedLayoutRunnersRoute,
  ProtectedLayoutIndexRoute: ProtectedLayoutIndexRoute,
  ProtectedLayoutSystemAuditLogsRoute:
    ProtectedLayoutSystemAuditLogsRouteWithChildren,
  ProtectedLayoutSystemSettingsRoute: ProtectedLayoutSystemSettingsRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

interface ProtectedProjectProjectsProjectIdContentTypesRouteChildren {
  ProtectedProjectProjectsProjectIdContentTypesIndexRoute: typeof ProtectedProjectProjectsProjectIdContentTypesIndexRoute
  ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute: typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute
  ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute: typeof ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute
}

const ProtectedProjectProjectsProjectIdContentTypesRouteChildren: ProtectedProjectProjectsProjectIdContentTypesRouteChildren =
  {
    ProtectedProjectProjectsProjectIdContentTypesIndexRoute:
      ProtectedProjectProjectsProjectIdContentTypesIndexRoute,
    ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute:
      ProtectedProjectProjectsProjectIdContentTypesContentTypeIdBuilderRoute,
    ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute:
      ProtectedProjectProjectsProjectIdContentTypesContentTypeIdIndexRoute,
  }

const ProtectedProjectProjectsProjectIdContentTypesRouteWithChildren =
  ProtectedProjectProjectsProjectIdContentTypesRoute._addFileChildren(
    ProtectedProjectProjectsProjectIdContentTypesRouteChildren,
  )

interface ProtectedProjectProjectsProjectIdContentsTypeKeyRouteChildren {
  ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute
  ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute
  ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute
}

const ProtectedProjectProjectsProjectIdContentsTypeKeyRouteChildren: ProtectedProjectProjectsProjectIdContentsTypeKeyRouteChildren =
  {
    ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute:
      ProtectedProjectProjectsProjectIdContentsTypeKeyNewRoute,
    ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute:
      ProtectedProjectProjectsProjectIdContentsTypeKeyIndexRoute,
    ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute:
      ProtectedProjectProjectsProjectIdContentsTypeKeyContentItemIdEditRoute,
  }

const ProtectedProjectProjectsProjectIdContentsTypeKeyRouteWithChildren =
  ProtectedProjectProjectsProjectIdContentsTypeKeyRoute._addFileChildren(
    ProtectedProjectProjectsProjectIdContentsTypeKeyRouteChildren,
  )

interface ProtectedProjectProjectsProjectIdContentsRouteChildren {
  ProtectedProjectProjectsProjectIdContentsTypeKeyRoute: typeof ProtectedProjectProjectsProjectIdContentsTypeKeyRouteWithChildren
  ProtectedProjectProjectsProjectIdContentsIndexRoute: typeof ProtectedProjectProjectsProjectIdContentsIndexRoute
}

const ProtectedProjectProjectsProjectIdContentsRouteChildren: ProtectedProjectProjectsProjectIdContentsRouteChildren =
  {
    ProtectedProjectProjectsProjectIdContentsTypeKeyRoute:
      ProtectedProjectProjectsProjectIdContentsTypeKeyRouteWithChildren,
    ProtectedProjectProjectsProjectIdContentsIndexRoute:
      ProtectedProjectProjectsProjectIdContentsIndexRoute,
  }

const ProtectedProjectProjectsProjectIdContentsRouteWithChildren =
  ProtectedProjectProjectsProjectIdContentsRoute._addFileChildren(
    ProtectedProjectProjectsProjectIdContentsRouteChildren,
  )

interface ProtectedProjectProjectsProjectIdRepositoriesRouteChildren {
  ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute
  ProtectedProjectProjectsProjectIdRepositoriesIndexRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesIndexRoute
}

const ProtectedProjectProjectsProjectIdRepositoriesRouteChildren: ProtectedProjectProjectsProjectIdRepositoriesRouteChildren =
  {
    ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute:
      ProtectedProjectProjectsProjectIdRepositoriesRepositoryIdRoute,
    ProtectedProjectProjectsProjectIdRepositoriesIndexRoute:
      ProtectedProjectProjectsProjectIdRepositoriesIndexRoute,
  }

const ProtectedProjectProjectsProjectIdRepositoriesRouteWithChildren =
  ProtectedProjectProjectsProjectIdRepositoriesRoute._addFileChildren(
    ProtectedProjectProjectsProjectIdRepositoriesRouteChildren,
  )

interface ProtectedProjectProjectsProjectIdStructsRouteChildren {
  ProtectedProjectProjectsProjectIdStructsIndexRoute: typeof ProtectedProjectProjectsProjectIdStructsIndexRoute
  ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute: typeof ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute
}

const ProtectedProjectProjectsProjectIdStructsRouteChildren: ProtectedProjectProjectsProjectIdStructsRouteChildren =
  {
    ProtectedProjectProjectsProjectIdStructsIndexRoute:
      ProtectedProjectProjectsProjectIdStructsIndexRoute,
    ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute:
      ProtectedProjectProjectsProjectIdStructsStructIdBuilderRoute,
  }

const ProtectedProjectProjectsProjectIdStructsRouteWithChildren =
  ProtectedProjectProjectsProjectIdStructsRoute._addFileChildren(
    ProtectedProjectProjectsProjectIdStructsRouteChildren,
  )

interface ProtectedProjectProjectsProjectIdRouteRouteChildren {
  ProtectedProjectProjectsProjectIdContentTypesRoute: typeof ProtectedProjectProjectsProjectIdContentTypesRouteWithChildren
  ProtectedProjectProjectsProjectIdContentsRoute: typeof ProtectedProjectProjectsProjectIdContentsRouteWithChildren
  ProtectedProjectProjectsProjectIdExecutorSettingsRoute: typeof ProtectedProjectProjectsProjectIdExecutorSettingsRoute
  ProtectedProjectProjectsProjectIdOverviewRoute: typeof ProtectedProjectProjectsProjectIdOverviewRoute
  ProtectedProjectProjectsProjectIdRepositoriesRoute: typeof ProtectedProjectProjectsProjectIdRepositoriesRouteWithChildren
  ProtectedProjectProjectsProjectIdStructsRoute: typeof ProtectedProjectProjectsProjectIdStructsRouteWithChildren
  ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute: typeof ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute
  ProtectedProjectProjectsProjectIdResourcesResourceIdRoute: typeof ProtectedProjectProjectsProjectIdResourcesResourceIdRoute
  ProtectedProjectProjectsProjectIdPipelineIndexRoute: typeof ProtectedProjectProjectsProjectIdPipelineIndexRoute
  ProtectedProjectProjectsProjectIdPipelineNodesNewRoute: typeof ProtectedProjectProjectsProjectIdPipelineNodesNewRoute
  ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute: typeof ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute
}

const ProtectedProjectProjectsProjectIdRouteRouteChildren: ProtectedProjectProjectsProjectIdRouteRouteChildren =
  {
    ProtectedProjectProjectsProjectIdContentTypesRoute:
      ProtectedProjectProjectsProjectIdContentTypesRouteWithChildren,
    ProtectedProjectProjectsProjectIdContentsRoute:
      ProtectedProjectProjectsProjectIdContentsRouteWithChildren,
    ProtectedProjectProjectsProjectIdExecutorSettingsRoute:
      ProtectedProjectProjectsProjectIdExecutorSettingsRoute,
    ProtectedProjectProjectsProjectIdOverviewRoute:
      ProtectedProjectProjectsProjectIdOverviewRoute,
    ProtectedProjectProjectsProjectIdRepositoriesRoute:
      ProtectedProjectProjectsProjectIdRepositoriesRouteWithChildren,
    ProtectedProjectProjectsProjectIdStructsRoute:
      ProtectedProjectProjectsProjectIdStructsRouteWithChildren,
    ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute:
      ProtectedProjectProjectsProjectIdPipelinePipelineIdRoute,
    ProtectedProjectProjectsProjectIdResourcesResourceIdRoute:
      ProtectedProjectProjectsProjectIdResourcesResourceIdRoute,
    ProtectedProjectProjectsProjectIdPipelineIndexRoute:
      ProtectedProjectProjectsProjectIdPipelineIndexRoute,
    ProtectedProjectProjectsProjectIdPipelineNodesNewRoute:
      ProtectedProjectProjectsProjectIdPipelineNodesNewRoute,
    ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute:
      ProtectedProjectProjectsProjectIdPipelineNodesIndexRoute,
  }

const ProtectedProjectProjectsProjectIdRouteRouteWithChildren =
  ProtectedProjectProjectsProjectIdRouteRoute._addFileChildren(
    ProtectedProjectProjectsProjectIdRouteRouteChildren,
  )

interface ProtectedProjectRouteChildren {
  ProtectedProjectProjectsProjectIdRouteRoute: typeof ProtectedProjectProjectsProjectIdRouteRouteWithChildren
}

const ProtectedProjectRouteChildren: ProtectedProjectRouteChildren = {
  ProtectedProjectProjectsProjectIdRouteRoute:
    ProtectedProjectProjectsProjectIdRouteRouteWithChildren,
}

const ProtectedProjectRouteWithChildren =
  ProtectedProjectRoute._addFileChildren(ProtectedProjectRouteChildren)

interface ProtectedRouteChildren {
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  ProtectedProjectRoute: typeof ProtectedProjectRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  ProtectedProjectRoute: ProtectedProjectRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface AuthRouteChildren {
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
